---
- name: Install EPEL repo.
  yum:
    name: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state: present

- name: nginx - install nginx
  yum: 
    name: http://nginx.org/packages/centos/6/x86_64/RPMS/nginx-1.6.2-1.el6.ngx.x86_64.rpm
    state: present

- name: nginx - install python-passlib
  yum: name=python-passlib state=latest

- name: nginx - install httpd-tools
  yum: name=httpd-tools state=latest

- name: nginx - htpasswd
  htpasswd: path=/etc/nginx/.htpasswd name=grafana password={{ HTPASSWD_GRAFANA_PASSWORD }} owner=root group=nginx mode=0640

- name: nginx - copy site
  template: src=grafana.conf dest=/etc/nginx/conf.d/

- name: nginx - remove default site
  file: path=/etc/nginx/conf.d/default.conf  state=absent

- name: nginx - restart
  service: name=nginx state=restarted
