#- name: install collectd on compute hosts
#  hosts: computehosts
#  vars_files:
#    - vars/external_vars.yml
#  user: root
#  roles:
#    - collectd-ubuntu
- name: install collectd on genomagicapi test
  hosts: test
  vars_files:
    - vars/external_vars.yml
  user: root
  roles:
    - collectd-centos

