#- name: install collectd on compute hosts
#  hosts: computehosts
#  vars_files:
#    - vars/external_vars.yml
#  user: root
#  roles:
#    - collectd-ubuntu
- name: install collectd on genomagicapi test
  hosts: collectd
  vars_files:
    - vars/external_vars.yml
  remote_user: ec2-user
  sudo: yes
  roles:
    - collectd-centos

