---
- name: install influx task
  hosts: influxservers
  vars_files:
    - vars/external_vars.yml
  remote_user: ec2-user
  sudo: yes
  roles:
    - influxdb

- name: install grafana task
  hosts: grafanaservers
  vars_files:
    - vars/external_vars.yml
  remote_user: ec2-user
  sudo: yes
  roles:
    - nginx
    - grafana
